CREATE INDEX address_addr_geom_gix ON public.address USING gist (geom) WHERE (kind = 'addr'::text);
CREATE INDEX address_bld_trgm ON public.address USING gin (bld gin_trgm_ops);
CREATE INDEX address_emd_trgm ON public.address USING gin (emd gin_trgm_ops) WHERE (kind <> 'addr'::text);
CREATE INDEX address_geom_gix ON public.address USING gist (geom);
CREATE INDEX address_kind_idx ON public.address USING btree (kind);
CREATE UNIQUE INDEX address_pkey ON public.address USING btree (id);
CREATE INDEX address_postal_idx ON public.address USING btree (postal) WHERE (kind = 'addr'::text);
CREATE INDEX address_region_idx ON public.address USING btree (sigungu, emd);
CREATE INDEX address_road_addr_idx ON public.address USING btree (road_norm, main_no, sub_no) WHERE (kind = 'addr'::text);
CREATE INDEX address_search_trgm ON public.address USING gin (search_text gin_trgm_ops);
CREATE INDEX address_sido_trgm ON public.address USING gin (sido gin_trgm_ops) WHERE (kind <> 'addr'::text);
CREATE INDEX address_sigungu_trgm ON public.address USING gin (sigungu gin_trgm_ops) WHERE (kind <> 'addr'::text);
CREATE INDEX address_source_idx ON public.address USING btree (source);
CREATE INDEX address_synth_pnu_idx ON public.address USING btree (((bcode || substr(bd_mgt_sn, 11, 9)))) WHERE (kind = 'addr'::text);
CREATE INDEX poi_geom_gix ON public.poi USING gist (geom);
CREATE INDEX poi_kind_idx ON public.poi USING btree (kind);
CREATE UNIQUE INDEX poi_pkey ON public.poi USING btree (id);
CREATE INDEX poi_primary_idx ON public.poi USING btree (is_primary);
CREATE INDEX poi_tier_idx ON public.poi USING btree (tier_minzoom);
